
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
              'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyCXWx205p0yW9hpMmxs0uOTZdSOCh_n698',
      appId: '1:244911606193:android:8cb01e01d4a3e7320a5590',
      messagingSenderId: '244911606193',
      projectId: 'petadoption-158ed',
      storageBucket: 'petadoption-158ed.appspot.com'
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyAAmLrY3_Yzks1OPX5CVAraOM3Cjof_U38',
      authDomain: 'petapp-d30f1.firebaseapp.com',
      projectId: 'petapp-d30f1',
      storageBucket: 'petapp-d30f1.appspot.com',
      messagingSenderId: '417494720081',
      appId: '1:417494720081:web:64fb9143564b874022a270',
      measurementId: 'G-QXWLFVVX5H'
  );
}
